In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator , SimpleImputer

In [4]:
df = pd.read_csv('train.csv',usecols=['Age' , 'Fare' , 'Survived'])

In [5]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [6]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [7]:
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.2 , random_state=42)

In [8]:
X_train.head()

      Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [9]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [11]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train_trf , y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6480446927374302

In [12]:
mi = MissingIndicator()
mi.fit(X_train)

MissingIndicator()

In [13]:
X_train_missing = mi.transform(X_train)

In [14]:
X_test_missing = mi.transform(X_test)

In [15]:
X_train['Age_NA'] = X_train_missing

In [16]:
X_test['Age_NA'] = X_test_missing

In [17]:
X_train

      Age      Fare  Age_NA
331  45.5   28.5000   False
733  23.0   13.0000   False
382  32.0    7.9250   False
704  26.0    7.8542   False
813   6.0   31.2750   False
..    ...       ...     ...
106  21.0    7.6500   False
270   NaN   31.0000    True
860  41.0   14.1083   False
435  14.0  120.0000   False
102  21.0   77.2875   False

[712 rows x 3 columns]

In [18]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.fit_transform(X_test)

In [19]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train_trf2 , y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6368715083798883

In [20]:
si = SimpleImputer(add_indicator=True)

In [21]:
X_train = si.fit_transform(X_train)

In [23]:
X_test = si.transform(X_test)

In [25]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train_trf2 , y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6368715083798883